import { listStockMovements } from "@/actions/inventory.actions";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { format } from "date-fns";

export default async function StockMovementsPage({ searchParams }: { searchParams: Promise<{ q?: string; type?: string; page?: string }> }) {
  const params = await searchParams;
  const data = await listStockMovements({ q: params.q, type: params.type, page: Number(params.page || 1) });
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">Stock movements</h1><p className="text-sm text-muted-foreground">Auditable history of stock changes in this store.</p></div><Link href="/inventory" className="text-sm text-primary">Inventory overview</Link></div>
    <form className="flex flex-wrap gap-2"><input name="q" defaultValue={params.q} placeholder="Search product, IMEI, reason" className="h-10 min-w-56 rounded-md border bg-background px-3 text-sm"/><select name="type" defaultValue={params.type||""} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All movement types</option>{["PURCHASE","SALE","SALE_RETURN","PURCHASE_RETURN","ADJUSTMENT_IN","ADJUSTMENT_OUT","DAMAGE","LOSS"].map((type)=><option key={type}>{type}</option>)}</select><button className="h-10 rounded-md bg-primary px-4 text-sm text-primary-foreground">Search</button><Link href="/inventory/movements" className="self-center text-sm text-muted-foreground">Clear</Link></form>
    <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b text-left text-muted-foreground">{["Date","Product","IMEI","Type","Qty","Previous","New","Reference / Batch","User","Reason"].map(x=><th key={x} className="p-3 font-medium">{x}</th>)}</tr></thead><tbody>{data.rows.map((m)=><tr key={m.id} className="border-b last:border-0"><td className="p-3">{format(m.createdAt,"yyyy-MM-dd HH:mm")}</td><td className="p-3">{m.product.model}</td><td className="p-3 font-mono text-xs">{m.inventory?.imei||"—"}</td><td className="p-3"><Badge variant="outline">{m.movementType}</Badge></td><td className="p-3">{m.quantity>0?`+${m.quantity}`:m.quantity}</td><td className="p-3">{m.previousStock}</td><td className="p-3">{m.newStock}</td><td className="p-3">{m.referenceType||"—"}{m.batch?` · ${m.batch.batchNumber}`:""}</td><td className="p-3">{m.createdBy.name}</td><td className="p-3">{m.reason||"—"}</td></tr>)}</tbody></table>{data.rows.length===0&&<p className="p-6 text-sm text-muted-foreground">No stock movements match these filters.</p>}</CardContent></Card>
    <div className="flex items-center justify-between text-sm"><span>{data.total} movement(s) · Page {data.page} of {data.pages}</span><div className="flex gap-3">{data.page>1&&<Link href={`?q=${encodeURIComponent(params.q||"")}&type=${params.type||""}&page=${data.page-1}`}>Previous</Link>}{data.page<data.pages&&<Link href={`?q=${encodeURIComponent(params.q||"")}&type=${params.type||""}&page=${data.page+1}`}>Next</Link>}</div></div>
  </div>;
}
