"use client";
import { useState } from "react";
import { getSupplierLedger } from "@/actions/suppliers.actions";
import { getCustomerLedger } from "@/actions/reports.actions";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { formatCurrency, formatDate } from "@/lib/utils";
import * as XLSX from "xlsx";

type Party={id:string;name:string};
export function LedgerReport({ suppliers, customers }: { suppliers:Party[]; customers:Party[] }) {
 const [kind,setKind]=useState("supplier"),[id,setId]=useState(""),[from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[ledger,setLedger]=useState<any>(null),[busy,setBusy]=useState(false);
 async function load(){if(!id)return;setBusy(true);const f=new Date(`${from}T00:00:00`),t=new Date(`${to}T23:59:59.999`);setLedger(kind==="supplier"?await getSupplierLedger(id,f,t):await getCustomerLedger(id,f,t));setBusy(false)}
 const entries=ledger?.entries??[];
 function exportLedger(format:"csv"|"xlsx") { if(!ledger)return; const rows=[{Date:from,Description:"Opening Balance",Debit:"",Credit:"",Balance:ledger.openingBalance},...entries.map((r:any)=>({Date:formatDate(r.date),Description:r.description,Debit:r.debit||"",Credit:r.credit||"",Balance:r.balance}))]; const ws=XLSX.utils.json_to_sheet(rows); if(format==="xlsx"){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Ledger");XLSX.writeFile(wb,"ledger.xlsx");}else{const blob=new Blob([XLSX.utils.sheet_to_csv(ws)],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="ledger.csv";a.click();URL.revokeObjectURL(url);} }
 return <div className="space-y-3"><div className="flex flex-wrap items-end gap-2"><div className="w-44"><label className="text-xs">Ledger Type</label><Select value={kind} onValueChange={v=>{setKind(v);setId("");setLedger(null)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="supplier">Supplier Ledger</SelectItem><SelectItem value="customer">Customer Ledger</SelectItem></SelectContent></Select></div><div className="w-56"><label className="text-xs">{kind} Select</label><Select value={id} onValueChange={setId}><SelectTrigger><SelectValue placeholder={`Select ${kind}`}/></SelectTrigger><SelectContent>{(kind==="supplier"?suppliers:customers).map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><label className="text-xs">From<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs">To<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button onClick={load} disabled={!id||busy}>{busy?"Loading…":"Apply"}</Button><Button variant="outline" onClick={()=>window.print()} disabled={!ledger}>Print</Button><Button variant="outline" onClick={()=>exportLedger("csv")} disabled={!ledger}>CSV</Button><Button variant="outline" onClick={()=>exportLedger("xlsx")} disabled={!ledger}>Excel</Button></div>
 {ledger&&<div id="ledger-print" className="space-y-3"><h3 className="font-semibold">{kind==="supplier"?ledger.supplier.name:ledger.customer.name} Ledger</h3><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Card><CardContent className="p-3 text-sm">Opening<br/><b>{formatCurrency(ledger.openingBalance)}</b></CardContent></Card><Card><CardContent className="p-3 text-sm">Total Debit<br/><b>{formatCurrency(ledger.totalDebit)}</b></CardContent></Card><Card><CardContent className="p-3 text-sm">Total Credit<br/><b>{formatCurrency(ledger.totalCredit)}</b></CardContent></Card><Card><CardContent className="p-3 text-sm">Closing<br/><b>{formatCurrency(ledger.closingBalance)}</b></CardContent></Card></div><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Date</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody><tr className="border-b"><td className="p-2">{formatDate(from)}</td><td>Opening Balance</td><td>—</td><td>—</td><td>{formatCurrency(ledger.openingBalance)}</td></tr>{entries.map((row:any,i:number)=><tr key={i} className="border-b"><td className="p-2">{formatDate(row.date)}</td><td>{row.batchId?<a className="text-primary underline" href={`/purchase#${row.batchId}`} title="View purchase batch">{row.description}</a>:row.description}</td><td>{row.debit?formatCurrency(row.debit):"—"}</td><td>{row.credit?formatCurrency(row.credit):"—"}</td><td>{formatCurrency(row.balance)}</td></tr>)}</tbody></table></div></div>}
 </div>;
}
